default: &default
  bot_token: <%= ENV['DISCORD_BOT_TOKEN'] %>
  channel_id: <%= ENV['DISCORD_CHANNEL_ID'] %>
  client_id: <%= ENV['DISCORD_CLIENT_ID'] %>
  client_secret: <%= ENV['DISCORD_CLIENT_SECRET'] %>

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default
