default: &default
  networks:
    "137":
      "0x7595e10C45CDd68cAb85F32Bc9d52EAD31da8965": "tween"
      "0x3f5C62b07a38BCE116fB5fCc61cBc262B43A3364": "pcl"
    "1284":
      "0xfb0e6023be6ce4ee03fa20382507afeafec56e28": "ifl"
    "80001":
      "0x3cd5c7f47c0933267aed07a115c8e5a3d0a30f22": "damat"
      "0xb098f0a6a27a67b529bb3bceeaa1efe7e93b1f7b": "tween"

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default
